name: CI / CD

on:
  push:
    branches: [ main ]

jobs:
  build-n-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - name: Build 🛠
        run: |
          yarn
          yarn build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: main
          folder: dist
          repository-name: digital4better/digital4better.github.io
          target-folder: cheque
          ssh-key: ${{ secrets.DEPLOY_KEY }}
